In [1]:
import tensorflow
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Flatten,Dense,Dropout,MaxPool2D,Conv2D

In [2]:
datagen = ImageDataGenerator(rescale= 1./255, shear_range= 0.2,zoom_range=0.1,horizontal_flip=True,validation_split=0.1)
train_data = datagen.flow_from_directory('D://AI ML DL//SLD//Data_set//ISL_new',target_size=(64,64),batch_size=32,class_mode='categorical',seed =10,subset='training')

validation_data = datagen.flow_from_directory('D://AI ML DL//SLD//Data_set//ISL_new',target_size=(64,64),class_mode='categorical',batch_size=32,seed =10,subset='validation')


#test_datagen = ImageDataGenerator(rescale=1./255)
#test_data = test_datagen.flow_from_directory('D:/AI ML DL/SLD/data_test',target_size=(128,128),batch_size=32,class_mode='categorical')

Found 4487 images belonging to 24 classes.
Found 485 images belonging to 24 classes.


In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [4]:
train_data

In [4]:
from tensorflow.keras import Sequential
model=Sequential()
model.add(Conv2D(filters=64,kernel_size=(3,3),input_shape=(64,64,3),activation='relu'))
model.add(MaxPool2D((2,2)))

model.add(Conv2D(filters=32,kernel_size=(3,3),activation='relu'))
model.add(MaxPool2D((2,2)))

#model.add(Conv2D(filters=128,kernel_size=(3,3),activation='relu'))
#model.add(MaxPool2D((2,2)))

model.add(Flatten())


#model.add(Dense(units=64 , activation='relu'))
#model.add(Dense(units=128 , activation='relu'))
model.add(Dense(units=128 , activation='relu'))
model.add(Dense(units=24 , activation='softmax'))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 64)        1792      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 64)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 29, 29, 32)        18464     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 6272)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               802944    
_________________________________________________________________
dense_1 (Dense)              (None, 24)                3

In [6]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics='accuracy')

In [12]:
history=model.fit(x=train_data,validation_data=validation_data,epochs=25,batch_size=32)

Epoch 1/25
141/141 [==============================] - 49s 345ms/step - loss: 0.0272 - accuracy: 0.9929 - val_loss: 1.1575 - val_accuracy: 0.7588
Epoch 2/25
141/141 [==============================] - 49s 351ms/step - loss: 0.0307 - accuracy: 0.9902 - val_loss: 1.3245 - val_accuracy: 0.7340
Epoch 3/25
141/141 [==============================] - 55s 388ms/step - loss: 0.0274 - accuracy: 0.9931 - val_loss: 1.0592 - val_accuracy: 0.7897
Epoch 4/25
141/141 [==============================] - 48s 343ms/step - loss: 0.0271 - accuracy: 0.9922 - val_loss: 1.1129 - val_accuracy: 0.7216
Epoch 5/25
141/141 [==============================] - 48s 341ms/step - loss: 0.0146 - accuracy: 0.9973 - val_loss: 1.3250 - val_accuracy: 0.7588
Epoch 6/25
141/141 [==============================] - 49s 347ms/step - loss: 0.0253 - accuracy: 0.9918 - val_loss: 1.1347 - val_accuracy: 0.7814
Epoch 7/25
141/141 [==============================] - 50s 355ms/step - loss: 0.0316 - accuracy: 0.9893 - val_loss: 1.1170 - val_ac

In [13]:
fname ="trained_model2.hdf5"
model.save(fname,overwrite=True)

In [20]:
y_pred = np.argmax(model.predict(test_data),axis =1)
y_pred

array([10,  6,  4, ..., 25, 31, 13], dtype=int64)

In [10]:
fname = "trained_model2.hdf5"
model.load_weights(fname)

In [11]:
y_pred = np.argmax(model.predict(test_data),axis =1)
y_pred

array([21, 20,  2, ...,  5, 16,  8], dtype=int64)

In [14]:
train_data.class_indices

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'K': 9,
 'L': 10,
 'M': 11,
 'N': 12,
 'O': 13,
 'P': 14,
 'Q': 15,
 'R': 16,
 'S': 17,
 'T': 18,
 'U': 19,
 'V': 20,
 'W': 21,
 'X': 22,
 'Y': 23}

In [15]:
y_true = np.argmax(model.predict(train_data),axis =1)
y_true

array([21, 15,  3, ..., 15,  7,  3], dtype=int64)

In [18]:
from keras.preprocessing import image
test_image =  image.load_img('D:\AI ML DL\SLD\Testing images\images.png',target_size=(64,64,3))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_classes(test_image)
result

array([23], dtype=int64)